cusac2spec: cusac2spec.cu fft.cu file.cu globalvar.cuh ini.cu makefile sac.cu \
			sac.cuh setnm.cu spec.cu spec.cuh utepoch.cu valid.cu
	nvcc cusac2spec.cu -o cusac2spec -lcufft -I /home/jzz/NVIDIA_CUDA-11.1_Samples/common/inc