cucorrelation:	cc.cu complex.cuh cucorrelation.cu fft.cu file.cu globalvar.cuh \
				gpumanage.cu ini.cu makefile spec.cuh
	nvcc cucorrelation.cu -o cucorrelation -lcufft -I /home/jzz/NVIDIA_CUDA-11.1_Samples/common/inc